server:
  port: 18000

spring:
  application:
    name: home
  main:
    allow-bean-definition-overriding: true
  messages:
    encoding: UTF-8
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  thymeleaf:
    encoding: UTF-8
    mode: HTML
    cache: false

logging:
  level:
    org:
      egovframe:
        rte: debug
      springframework:
        boot:
          autoconfigure: error
        web: debug
    egovframework:
      com: debug

eureka:
  client:
    register-with-eureka: true # Eureka 등록 여부
    fetch-registry: true # Eureka 조회 여부
    registry-fetch-interval-seconds: 5 # 클라이어트 측에서 레지스트리를 캐싱하는 시간
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    instance:
      lease-renewal-interval-in-seconds: 3  # 기본값 30초 → 3초로 변경 (더 자주 heartbeat 전송)
      lease-expiration-duration-in-seconds: 10  # 기본값 90초 → 10초로 변경 (서비스 제거 시간 단축)
      instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

management:
  endpoints:
    web:
      exposure:
        include: health, info
